server:
  port: 8080
  connection-timeout: 30m
  tomcat:
    max-threads: 30
    uri-encoding: utf-8
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  mvc:
    favicon:
      enabled: false
  aop:
    auto: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
  type-aliases-package: net.orangepeels.model
  mapper-locations: classpath:/mapper/*.xml