server:
  port: 8080
  connection-timeout: 30m
  tomcat:
    max-threads: 10
    uri-encoding: utf-8
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  profiles:
    active: dev
  thymeleaf:
    prefix: /templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
mybatis:
  mapper-locations: /mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
